'use client';
import {FormEvent,useState} from 'react';
import {DirectSend} from './direct-send';
const choices={Hiring:{label:'I’m hiring',hint:'A role with your team',detail:'Company & role',extra:'Work arrangement / location',placeholder:'Company · Full Stack Developer'},Collaboration:{label:'Let’s collaborate',hint:'Build something together',detail:'Project / idea',extra:'Where could I contribute?',placeholder:'What are you working on?'},Freelance:{label:'I have a project',hint:'A freelance enquiry',detail:'Project scope',extra:'Timeline & budget (optional)',placeholder:'What would you like to build?'}};
type Purpose=keyof typeof choices;
export function ContactForm(){
 const [purpose,setPurpose]=useState<Purpose>('Hiring'),[errors,setErrors]=useState<Record<string,string>>({}),[brief,setBrief]=useState<{subject:string;body:string;email:string}|null>(null),[copied,setCopied]=useState('Copy message');
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get('name')||'').trim(),email=String(f.get('email')||'').trim(),detail=String(f.get('detail')||'').trim(),extra=String(f.get('extra')||'').trim(),message=String(f.get('message')||'').trim(),next:Record<string,string>={};if(name.length<2)next.name='Please enter your name.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))next.email='Enter a valid email address.';if(detail.length<3)next.detail='Add a little context.';if(message.length<15)next.message='Please add at least 15 characters.';setErrors(next);if(Object.keys(next).length){e.currentTarget.querySelector<HTMLInputElement>('[name="'+Object.keys(next)[0]+'"]')?.focus();return}setCopied('Copy message');setBrief({email,subject:purpose+': '+detail,body:'Hi Harsh,\n\n'+message+'\n\n'+choices[purpose].detail+': '+detail+'\n'+choices[purpose].extra+': '+(extra||'To discuss')+'\n\nFrom: '+name+'\nEmail: '+email})}
 async function copy(){if(!brief)return;try{await navigator.clipboard.writeText(brief.subject+'\n\n'+brief.body);setCopied('Copied ✓')}catch{setCopied('Copy from the preview below')}}
 return <form className="contact-form guided-form" onSubmit={submit} noValidate><header><span>{brief?'03 / REVIEW':'01 / YOUR DIRECTION'}</span><b>{brief?'Your introduction, ready.':'Choose a starting point.'}</b></header>{!brief?<><fieldset className="purpose-options"><legend className="sr-only">Reason for contacting</legend>{(Object.keys(choices) as Purpose[]).map(p=><label key={p} className={purpose===p?'selected':''}><input type="radio" name="purpose" value={p} checked={purpose===p} onChange={()=>setPurpose(p)}/><strong>{choices[p].label}</strong><span>{choices[p].hint}</span></label>)}</fieldset><p className="form-step">02 / THE ESSENTIALS</p><label>Your name<input name="name" autoComplete="name" maxLength={100} aria-invalid={!!errors.name} aria-describedby={errors.name?'name-error':undefined}/>{errors.name&&<small id="name-error">{errors.name}</small>}</label><label>Your email<input name="email" type="email" autoComplete="email" maxLength={254} aria-invalid={!!errors.email} aria-describedby={errors.email?'email-error':undefined}/>{errors.email&&<small id="email-error">{errors.email}</small>}</label><label>{choices[purpose].detail}<input name="detail" placeholder={choices[purpose].placeholder} maxLength={180} aria-invalid={!!errors.detail} aria-describedby={errors.detail?'detail-error':undefined}/>{errors.detail&&<small id="detail-error">{errors.detail}</small>}</label><label>{choices[purpose].extra}<input name="extra" maxLength={180}/></label><label className="message-field">A little more detail<textarea name="message" rows={5} maxLength={2500} placeholder="The opportunity, what matters, and your ideal next step…" aria-invalid={!!errors.message} aria-describedby={errors.message?'message-error':undefined}/>{errors.message&&<small id="message-error">{errors.message}</small>}</label><button type="submit">Review my brief ↗</button><p>Nothing is sent or stored when you review.</p></>:<div className="brief-review"><p className="draft-notice">Draft prepared — not sent. Open your email app to review and send it, or copy the message.</p><strong>{brief.subject}</strong><pre>{brief.body}</pre><DirectSend subject={brief.subject} text={brief.body} email={brief.email}/><div className="review-actions"><a href={'mailto:hrsshhh17shukla06@gmail.com?subject='+encodeURIComponent(brief.subject)+'&body='+encodeURIComponent(brief.body)}>Open email draft ↗</a><button type="button" onClick={copy} aria-live="polite">{copied}</button><button type="button" onClick={()=>setBrief(null)}>Start another brief</button></div></div>}</form>
}