'use client';
import {Canvas,useFrame,useThree} from '@react-three/fiber';import {Float,Stars} from '@react-three/drei';import {useRef} from 'react';import * as THREE from 'three';import {projects,Project} from '@/lib/projects';
function Rig(){const {camera,pointer}=useThree();useFrame(()=>{camera.position.x=THREE.MathUtils.lerp(camera.position.x,pointer.x*.35,.025);camera.position.y=THREE.MathUtils.lerp(camera.position.y,pointer.y*.2,.025);camera.lookAt(.9,0,0)});return null}
function Core(){const g=useRef<THREE.Group>(null);useFrame((s,d)=>{if(g.current){g.current.rotation.y+=d*.12;g.current.rotation.z=Math.sin(s.clock.elapsedTime*.2)*.08}});return <group ref={g} position={[1.25,.55,0]}><mesh><icosahedronGeometry args={[1.15,4]}/><meshStandardMaterial color="#2a0905" emissive="#ff7a22" emissiveIntensity={3} metalness={.82} roughness={.12}/></mesh><mesh><icosahedronGeometry args={[1.24,2]}/><meshBasicMaterial color="#ffd089" wireframe transparent opacity={.5}/></mesh>{[0,1,2,3].map(i=><mesh key={i} rotation={[i*.67,i*.4,i*.53]}><torusGeometry args={[1.55+i*.19,.035,12,130]}/><meshStandardMaterial color={i%2?'#ff7130':'#e3b66c'} emissive="#b13b12" emissiveIntensity={1.2} metalness={1} roughness={.1}/></mesh>)}<pointLight color="#ff7627" intensity={20} distance={7}/></group>}
function Icon({i}:{i:number}){return i%3===0?<mesh><torusKnotGeometry args={[.22,.065,70,10]}/><meshBasicMaterial color="#ffc778"/></mesh>:i%3===1?<mesh><icosahedronGeometry args={[.3,1]}/><meshBasicMaterial color="#ff8a3d" wireframe/></mesh>:<group>{Array.from({length:9},(_,n)=><mesh key={n} position={[(n-4)*.055,0,0]} scale={[1,.25+Math.sin(n*2.1)**2,1]}><boxGeometry args={[.025,.42,.025]}/><meshBasicMaterial color={n%2?'#ffd184':'#ff5930'}/></mesh>)}</group>}
function World({p,i,onSelect}:{p:Project;i:number;onSelect:(p:Project)=>void}){const ps:[number,number,number][]=[[-.4,2.35,0],[3.75,2.05,0],[-1.15,.5,.1],[4.15,.25,.1],[.05,-1.55,.1],[3.75,-1.45,.1]];return <Float speed={1.2+i*.08} rotationIntensity={.16} floatIntensity={.25}><group position={ps[i]} onClick={()=>onSelect(p)} onPointerOver={()=>document.body.style.cursor='pointer'} onPointerOut={()=>document.body.style.cursor='auto'}><mesh><sphereGeometry args={[.58,32,32]}/><meshPhysicalMaterial color="#170706" transparent opacity={.8} metalness={.45} roughness={.08} transmission={.25} emissive={p.color} emissiveIntensity={.18}/></mesh><Icon i={i}/><mesh rotation={[1.2,0,.16]}><torusGeometry args={[.78,.024,10,80]}/><meshBasicMaterial color={p.color}/></mesh><pointLight color={p.color} intensity={3} distance={2}/></group></Float>}
function Ground(){return <group><mesh rotation={[-Math.PI/2,0,0]} position={[0,-2.7,0]}><planeGeometry args={[18,11]}/><meshStandardMaterial color="#080304" metalness={.95} roughness={.18}/></mesh>{Array.from({length:30},(_,i)=><mesh key={i} position={[i/29*10-5,-2.55,-.2+(i%5)*.22]} rotation={[i*.6,i*.3,i]} scale={.16+(i%4)*.08}><dodecahedronGeometry/><meshStandardMaterial color={i%5===0?'#4b1008':'#130809'} roughness={.8} emissive={i%5===0?'#891b09':'#000'} emissiveIntensity={.6}/></mesh>)}</group>}
function Portal(){const r=useRef<THREE.Mesh>(null);useFrame((s)=>{if(r.current)r.current.rotation.z=s.clock.elapsedTime*.2});return <group position={[1.15,-2.05,.35]}><mesh ref={r}><torusGeometry args={[.52,.05,14,90]}/><meshBasicMaterial color="#ffd086"/></mesh><mesh><circleGeometry args={[.44,42]}/><meshBasicMaterial color="#ff852f" transparent opacity={.22}/></mesh><pointLight color="#ff7b28" intensity={8} distance={3}/></group>}
export default function CosmicScene({onSelect}:{onSelect:(p:Project)=>void}){return <Canvas camera={{position:[0,0,8.5],fov:46}} dpr={[1,1.5]}><color attach="background" args={['#020101']}/><fog attach="fog" args={['#080203',8,15]}/><Rig/><ambientLight intensity={.38}/><directionalLight position={[1,5,5]} color="#ffd2a0" intensity={2}/><Stars radius={35} depth={18} count={2400} factor={2.5} fade speed={.25}/><Core/>{projects.map((p,i)=><World key={p.slug} p={p} i={i} onSelect={onSelect}/>)}<Portal/><Ground/></Canvas>}
