'use client';
import {useEffect,useRef,useState} from 'react';
type Turnstile={render:(element:HTMLElement,options:Record<string,unknown>)=>string;remove:(id:string)=>void;reset:(id:string)=>void};
declare global{interface Window{turnstile?:Turnstile}}
export function DirectSend({subject,text,email}:{subject:string;text:string;email:string}){
 const [siteKey,setSiteKey]=useState(''),[token,setToken]=useState(''),[status,setStatus]=useState<'idle'|'sending'|'sent'|'error'>('idle'),[message,setMessage]=useState('');const container=useRef<HTMLDivElement>(null),widget=useRef(''),requestId=useRef('');
 useEffect(()=>{const controller=new AbortController();fetch('/api/contact',{signal:controller.signal}).then(r=>r.json() as Promise<{enabled:boolean;siteKey?:string}>).then(c=>{if(c.enabled&&c.siteKey)setSiteKey(c.siteKey)}).catch(()=>{});return()=>controller.abort()},[]);
 useEffect(()=>{if(!siteKey)return;let cancelled=false;const mount=()=>{if(cancelled||!container.current||!window.turnstile||widget.current)return;widget.current=window.turnstile.render(container.current,{sitekey:siteKey,action:'contact',theme:'dark',callback:(t:string)=>setToken(t),'expired-callback':()=>setToken(''),'error-callback':()=>{setToken('');setMessage('Verification could not load. The email draft is still available.')}})};let script=document.querySelector<HTMLScriptElement>('script[data-turnstile]');if(!script){script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.dataset.turnstile='true';document.head.appendChild(script)}script.addEventListener('load',mount);mount();return()=>{cancelled=true;script?.removeEventListener('load',mount);if(widget.current)window.turnstile?.remove(widget.current);widget.current=''}},[siteKey]);
 async function send(){if(!token||status==='sending'||status==='sent')return;setStatus('sending');setMessage('');requestId.current||=crypto.randomUUID();try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject,text,email,token,website:'',id:requestId.current}),signal:AbortSignal.timeout(30000)});const data=await r.json() as {accepted?:boolean;error?:string};if(!r.ok||!data.accepted)throw new Error(data.error||'Unable to send.');setStatus('sent');setMessage('Your message was accepted by the email service. Thank you for reaching out.')}catch(e){setStatus('error');setMessage(e instanceof Error?e.message:'Unable to send. Please use the email draft.');setToken('');if(widget.current)window.turnstile?.reset(widget.current)}}
 if(!siteKey)return null;
 return <div className="direct-send"><p>Or send directly from this page after verification.</p><div ref={container}/><button type="button" disabled={!token||status==='sending'||status==='sent'} onClick={send}>{status==='sending'?'Sending…':status==='sent'?'Message accepted ✓':'Send to Harsh ↗'}</button><p role={status==='error'?'alert':'status'}>{message}</p></div>;
}
