'use client';
import {useRef,useState} from 'react';import {projects,Project} from '@/lib/projects';import {Brand} from './brand';
const points=[{x:43.2,y:13.7},{x:76.7,y:13.8},{x:36.6,y:38.2},{x:83.4,y:36.9},{x:43.8,y:68.2},{x:80.5,y:68.1}];
export default function HomeExperience(){const stage=useRef<HTMLElement>(null);const [selected,setSelected]=useState<Project|null>(null);const open=(p:Project)=>{if(selected)return;setSelected(p);setTimeout(()=>window.location.assign(`/projects/${p.slug}`),1450)};const move=(e:React.PointerEvent)=>{const el=stage.current;if(!el)return;const r=el.getBoundingClientRect();el.style.setProperty('--mx',`${((e.clientX-r.left)/r.width-.5)*-10}px`);el.style.setProperty('--my',`${((e.clientY-r.top)/r.height-.5)*-7}px`)};return <main ref={stage} className="cinema-home" onPointerMove={move}><div className="cosmic-art" aria-hidden="true"/><div className="cosmic-vignette"/>
<nav className="image-nav" aria-label="Primary navigation"><a href="/">HOME</a><a href="#projects">WORK</a><a href="/about">ABOUT</a><a href="/contact">CONTACT</a></nav>
<section id="projects" className="hotspot-layer" aria-label="Project worlds">{projects.map((p,i)=><button key={p.slug} className="project-hotspot" style={{left:`${points[i].x}%`,top:`${points[i].y}%`}} onClick={()=>open(p)} aria-label={`Explore ${p.name}`}><i/><span>{p.name}</span></button>)}</section>
<button className="portal-hit" onClick={()=>open(projects[0])} aria-label="Enter the project system"><span>ENTER SYSTEM</span></button>
<p className="interaction-hint">MOVE TO EXPLORE · SELECT A WORLD</p>
<section className="mobile-console"><p>SELECT A PROJECT WORLD</p><div>{projects.map((p,i)=><button key={p.slug} onClick={()=>open(p)}><small>0{i+1}</small><span>{p.name}</span><b>↗</b></button>)}</div><nav><a href="/about">ABOUT</a><a href="/contact">CONTACT</a></nav></section>
{selected&&<div className="transition" role="status"><Brand/><p>ENTERING PROJECT WORLD</p><h2>{selected.name}</h2><span>{selected.description}</span><div className="progress"><i/></div></div>}</main>}
