export type Project = { slug:string; name:string; eyebrow:string; description:string; stack:string[]; live:string; github:string; color:string; category:'Full Stack'|'AI'|'Frontend'|'3D'; challenge:string; solution:string; architecture:string[]; highlights:string[] };
export const projects: Project[] = [
 {slug:'converge',name:'CONVERGE',eyebrow:'Full-stack social platform',description:'A social application built around real-time connection, structured communities and secure user interaction.',stack:['React','Node.js','Express','MongoDB','REST APIs'],live:'https://converge-nu-eight.vercel.app',github:'https://github.com/hrsshhh17/converge',color:'#ffb85c',category:'Full Stack',challenge:'Design a cohesive social product where identity, content and community interactions feel connected instead of becoming separate demo features.',solution:'Built a complete client-server flow with structured API boundaries, persistent data and a responsive interface designed around real user journeys.',architecture:['React client','Express REST API','MongoDB data layer','Deployment pipeline'],highlights:['End-to-end application structure','Persistent social data','Responsive product interface']},
 {slug:'supportflow-ai',name:'SUPPORTFLOW AI',eyebrow:'AI-assisted support system',description:'A practical support workflow that combines application logic with AI assistance for faster, clearer customer conversations.',stack:['Next.js','TypeScript','AI APIs','Supabase'],live:'https://supportflow-ai-beta.vercel.app',github:'https://github.com/hrsshhh17/supportflow-ai',color:'#ff6b45',category:'AI',challenge:'Turn AI assistance into a useful support workflow rather than a disconnected chat demonstration.',solution:'Designed an application flow that connects support context, structured UI states and AI-generated assistance in one focused experience.',architecture:['Next.js interface','Typed application layer','AI service integration','Supabase persistence'],highlights:['AI-assisted workflow','Type-safe implementation','Product-focused UX']},
 {slug:'aether',name:'AETHER',eyebrow:'Futuristic AI experience',description:'A premium technology experience using cinematic motion, responsive layouts and a strong visual narrative.',stack:['React','Vite','GSAP','Responsive UI'],live:'https://aether-rosy-three.vercel.app/',github:'https://github.com/hrsshhh17/aether',color:'#e6c27a',category:'Frontend',challenge:'Present an abstract AI concept with enough clarity and visual hierarchy to remain usable across screen sizes.',solution:'Combined modular React sections, responsive typography and controlled motion to create a coherent premium narrative.',architecture:['React components','Vite build system','GSAP motion layer','Responsive CSS'],highlights:['Cinematic presentation','Responsive layouts','Purposeful motion system']},
 {slug:'sonic',name:'SONIC',eyebrow:'Immersive music experience',description:'An energetic festival world with rich motion, multimedia storytelling and interactive 3D presentation.',stack:['React','Vite','Three.js','GSAP'],live:'https://sonic-rho-six.vercel.app/',github:'https://github.com/hrsshhh17/sonic',color:'#ff8b68',category:'3D',challenge:'Coordinate audio-visual energy, content readability and runtime performance in one immersive festival experience.',solution:'Created a component-driven multimedia interface with timed animation, 3D presentation and responsive fallbacks.',architecture:['React experience shell','Three.js scene layer','GSAP timelines','Media asset pipeline'],highlights:['Interactive 3D','Multimedia integration','Motion-led storytelling']},
 {slug:'veyra',name:'VEYRA',eyebrow:'Cinematic travel experience',description:'A responsive travel story shaped through atmospheric visuals, fluid transitions and production-ready metadata.',stack:['React','Vite','GSAP','SEO'],live:'https://veyra-chi-one.vercel.app',github:'https://github.com/hrsshhh17/veyra',color:'#ffd492',category:'Frontend',challenge:'Build an atmospheric travel experience while retaining discoverability, responsive behaviour and fast navigation.',solution:'Structured cinematic sections around reusable frontend components, optimized metadata and restrained animation.',architecture:['React page system','GSAP transitions','SEO metadata','Vercel deployment'],highlights:['Visual storytelling','Search metadata','Production deployment']},
 {slug:'velocity-x132',name:'VELOCITY X132',eyebrow:'Interactive 3D automotive world',description:'A scroll-driven 3D experience that turns an automotive concept into an explorable digital product story.',stack:['React','Three.js','R3F','Drei','GSAP'],live:'https://velocity-x132.vercel.app',github:'https://github.com/hrsshhh17/velocity-x132',color:'#d88950',category:'3D',challenge:'Make a real-time 3D automotive scene respond naturally to scrolling without losing content hierarchy.',solution:'Connected a React Three Fiber scene to controlled scroll timelines, camera movement and responsive interface layers.',architecture:['React application','R3F scene graph','Drei helpers','GSAP scroll control'],highlights:['Real-time 3D scene','Scroll-driven camera','Responsive interaction']}
];
export const projectBySlug=(slug:string)=>projects.find(p=>p.slug===slug);
