export type Project = { slug:string; name:string; eyebrow:string; description:string; stack:string[]; live:string; github:string; color:string };
export const projects: Project[] = [
 {slug:'converge',name:'CONVERGE',eyebrow:'Full-stack social platform',description:'A social application built around real-time connection, structured communities and secure user interaction.',stack:['React','Node.js','Express','MongoDB','REST APIs'],live:'https://converge-nu-eight.vercel.app',github:'https://github.com/hrsshhh17/converge',color:'#ffb85c'},
 {slug:'supportflow-ai',name:'SUPPORTFLOW AI',eyebrow:'AI-assisted support system',description:'A practical support workflow that combines application logic with AI assistance for faster, clearer customer conversations.',stack:['Next.js','TypeScript','AI APIs','Supabase'],live:'https://supportflow-ai-beta.vercel.app',github:'https://github.com/hrsshhh17/supportflow-ai',color:'#ff6b45'},
 {slug:'aether',name:'AETHER',eyebrow:'Futuristic AI experience',description:'A premium technology experience using cinematic motion, responsive layouts and a strong visual narrative.',stack:['React','Vite','GSAP','Responsive UI'],live:'https://aether-rosy-three.vercel.app/',github:'https://github.com/hrsshhh17/aether',color:'#e6c27a'},
 {slug:'sonic',name:'SONIC',eyebrow:'Immersive music experience',description:'An energetic festival world with rich motion, multimedia storytelling and interactive 3D presentation.',stack:['React','Vite','Three.js','GSAP'],live:'https://sonic-rho-six.vercel.app/',github:'https://github.com/hrsshhh17/sonic',color:'#ff8b68'},
 {slug:'veyra',name:'VEYRA',eyebrow:'Cinematic travel experience',description:'A responsive travel story shaped through atmospheric visuals, fluid transitions and production-ready metadata.',stack:['React','Vite','GSAP','SEO'],live:'https://veyra-chi-one.vercel.app',github:'https://github.com/hrsshhh17/veyra',color:'#ffd492'},
 {slug:'velocity-x132',name:'VELOCITY X132',eyebrow:'Interactive 3D automotive world',description:'A scroll-driven 3D experience that turns an automotive concept into an explorable digital product story.',stack:['React','Three.js','R3F','Drei','GSAP'],live:'https://velocity-x132.vercel.app',github:'https://github.com/hrsshhh17/velocity-x132',color:'#d88950'}
];
export const projectBySlug=(slug:string)=>projects.find(p=>p.slug===slug);
